# Generated by Django 4.2.6 on 2023-10-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('dataNascimento', models.DateTimeField(max_length=10)),
                ('endereco', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
